### ISSUE TITLE
[Install Error] CUDA 12.1 mismatch Pytorch 

### ISSUE THREAD

**Issue by SwartzMss** [OpenBMB/BMTrain#100]
执行命令：
python setup.py install

报错信息：
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.8). Please make sure to use the same CUDA versions.

疑问：
目前pytorch的话 还没CUDA12.1 的版本，这样的报错有啥办法可以解决吗？

**Comment by youyajike** [comment]
RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> bmtrain
我也遇到了 我的cuda版本是12.1

**Comment by Achazwl** [comment]
New version of BMTrain fix this now.
