### ISSUE TITLE
bmtrain编译不过去啊，说是nccl问题，我是window环境

### ISSUE THREAD

**Issue by zhangweia** [OpenBMB/BMTrain#103]
8-win_amd64.exp
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommInitRank
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduce
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclRecv
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupEnd
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclSend
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommCount
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetUniqueId
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommDestroy

**Comment by acbogeh** [comment]
我和你一样

**Comment by menghuu** [comment]
cuda 装好了吗？ cuda-dev 装好了吗？

一个可供参考的conda环境创建命令

```bash
conda create --prefix $(pwd)/.conda_env pytorch==1.13.1 pytorch-cuda=11.6 libcusolver-dev -c pytorch -c nvidia
```

**Comment by Xinrihui** [comment]
同样的问题

**Comment by ShuaiLing-Shao** [comment]
同样的问题 解决了吗？

**Comment by MayDomine** [comment]
#123
