### ISSUE TITLE
cuda118 python2.0.0  C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe下，安装报错

### ISSUE THREAD

**Issue by acbogeh** [OpenBMB/BMTrain#106]
(cpm-bee) F:\AI\CPM-Bee-main\src>pip install bmtrain>=0.2.1
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1288 lines of output]
      running bdist_wheel
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
     。。。。。。。。。。。。。。
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/lbfgs.h(49): note:  查看对正在编译的 类 模板 实例化“c10::optional<std::vector<at::Tensor,std::allocator<at::Tensor>>>”的引用
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/Optional.h(446): warning C4624: “c10::trivially_copyable_optimization_optional_base<T>”: 已将析构函数隐式定义为“已删除”
              with
              [
                  T=std::vector<at::Tensor,std::allocator<at::Tensor>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\pybind11\detail/common.h(152): warning C4005: “HAVE_SNPRINTF”: 宏重定义
      D:\miniconda3\envs\cpm-bee\include\pyerrors.h(315): note: 参见“HAVE_SNPRINTF”的前一个定义
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(171): warning C4624: “ska::detailv3::sherwood_v3_entry<std::pair<K,V>>”: 已将析构函数隐式定义为“已删除”
              with
              [
                  K=std::string,
                  V=std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(779): note: 查看对正在编译的  类 模板 实例化“ska::detailv3::sherwood_v3_entry<std::pair<K,V>>”的引用
              with
              [
                  K=std::string,
                  V=std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(775): note: 在编译 类 模板 成 员函数“ska::detailv3::sherwood_v3_entry<std::pair<K,V>> *ska::detailv3::sherwood_v3_table<std::pair<K,V>,K,H,ska::detailv3::KeyOrValueHasher<K,std::pair<K,V>,H>,E,ska::detailv3::KeyOrValueEquality<K,std::pair<K,V>,E>,A,std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<K,V>>>>::empty_default_table(void)”时
              with
              [
                  K=std::string,
                  V=std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>,
                  H=std::hash<std::string>,
                  E=std::equal_to<std::string>,
                  A=std::allocator<std::pair<std::string,std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(768): note: 查看对正在编译的函数 模板 实例化“ska::detailv3::sherwood_v3_entry<std::pair<K,V>> *ska::detailv3::sherwood_v3_table<std::pair<K,V>,K,H,ska::detailv3::KeyOrValueHasher<K,std::pair<K,V>,H>,E,ska::detailv3::KeyOrValueEquality<K,std::pair<K,V>,E>,A,std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<K,V>>>>::empty_default_table(void)”的引用
              with
              [
                  K=std::string,
                  V=std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>,
                  H=std::hash<std::string>,
                  E=std::equal_to<std::string>,
                  A=std::allocator<std::pair<std::string,std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(1938): note: 查看对正在编译的 类 模板 实例化“ska::detailv3::sherwood_v3_table<std::pair<K,V>,K,H,ska::detailv3::KeyOrValueHasher<K,std::pair<K,V>,H>,E,ska::detailv3::KeyOrValueEquality<K,std::pair<K,V>,E>,A,std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<K,V>>>>”的引用
              with
              [
                  K=std::string,
                  V=std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>,
                  H=std::hash<std::string>,
                  E=std::equal_to<std::string>,
                  A=std::allocator<std::pair<std::string,std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\torch\csrc\api\include\torch/optim/optimizer.h(174): note: 查看对正在编译的 类 模板 实例化“ska::flat_hash_map<std::string,std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<K,V>>>”的引用
              with
              [
                  K=std::string,
                  V=std::unique_ptr<torch::optim::OptimizerParamState,std::default_delete<torch::optim::OptimizerParamState>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(171): warning C4624: “ska::detailv3::sherwood_v3_entry<std::pair<K,V>>”: 已将析构函数隐式定义为“已删除”
              with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(711): note: 查看对正在编译的  类 模板 实例化“ska::detailv3::sherwood_v3_entry<std::pair<K,V>>”的引用
              with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(708): note: 在编译 类 模板 成 员函数“void ska::detailv3::sherwood_v3_table<std::pair<K,V>,K,H,ska::detailv3::KeyOrValueHasher<K,std::pair<K,V>,H>,E,ska::detailv3::KeyOrValueEquality<K,std::pair<K,V>,E>,A,std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<K,V>>>>::clear(void)”时
              with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>,
                  H=std::hash<c10::DispatchKey>,
                  E=std::equal_to<c10::DispatchKey>,
                  A=std::allocator<std::pair<c10::DispatchKey,std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(431): note: 查看对正在编译的函数 模板 实例化“void ska::detailv3::sherwood_v3_table<std::pair<K,V>,K,H,ska::detailv3::KeyOrValueHasher<K,std::pair<K,V>,H>,E,ska::detailv3::KeyOrValueEquality<K,std::pair<K,V>,E>,A,std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<K,V>>>>::clear(void)”的引用
              with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>,
                  H=std::hash<c10::DispatchKey>,
                  E=std::equal_to<c10::DispatchKey>,
                  A=std::allocator<std::pair<c10::DispatchKey,std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\c10/util/flat_hash_map.h(1938): note: 查看对正在编译的 类 模板 实例化“ska::detailv3::sherwood_v3_table<std::pair<K,V>,K,H,ska::detailv3::KeyOrValueHasher<K,std::pair<K,V>,H>,E,ska::detailv3::KeyOrValueEquality<K,std::pair<K,V>,E>,A,std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<K,V>>>>”的引用
              with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>,
                  H=std::hash<c10::DispatchKey>,
                  E=std::equal_to<c10::DispatchKey>,
                  A=std::allocator<std::pair<c10::DispatchKey,std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>>>
              ]
      D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\include\ATen/core/dispatch/OperatorEntry.h(270): note: 查看对正在编译的 类 模板 实例化“ska::flat_hash_map<c10::DispatchKey,std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>,std::hash<c10::DispatchKey>,std::equal_to<K>,std::allocator<std::pair<K,V>>>”的引用
              with
              [
                  K=c10::DispatchKey,
                  V=std::list<c10::impl::AnnotatedKernel,std::allocator<c10::impl::AnnotatedKernel>>
              ]
      "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\miniconda3\envs\cpm-bee\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" /LIBPATH:D:\miniconda3\envs\cpm-bee\libs /LIBPATH:D:\miniconda3\envs\cpm-bee /LIBPATH:D:\miniconda3\envs\cpm-bee\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit__C build\temp.win-amd64-cpython-38\Release\csrc/nccl.obj /OUT:build\lib.win-amd64-cpython-38\bmtrain\nccl\_C.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-38\Release\csrc\_C.cp38-win_amd64.lib
        正在创建库 build\temp.win-amd64-cpython-38\Release\csrc\_C.cp38-win_amd64.lib 和对象 build\temp.win-amd64-cpython-38\Release\csrc\_C.cp38-win_amd64.exp
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommInitRank
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduce
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclRecv
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupEnd
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclSend
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommCount
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetUniqueId
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommDestroy
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclBroadcast
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupStart
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommUserRank
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduceScatter
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclAllGather
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclAllReduce
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetErrorString
      build\lib.win-amd64-cpython-38\bmtrain\nccl\_C.cp38-win_amd64.pyd : fatal error LNK1120: 15 个无法解析的外部命令
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

**Comment by nigowl** [comment]
+1

**Comment by zhaofeng45** [comment]
+1

**Comment by xiaoguaishoubaobao** [comment]
+1

**Comment by Xinrihui** [comment]
+1

**Comment by MayDomine** [comment]
see in #123
