### ISSUE TITLE
你好 安装报错 linux 

### ISSUE THREAD

**Issue by xiaoguaishoubaobao** [OpenBMB/BMTrain#112]
![image](https://github.com/OpenBMB/BMTrain/assets/21216881/da468fdb-912f-4105-8cc9-1af3d09c5122)
![image](https://github.com/OpenBMB/BMTrain/assets/21216881/9618f378-5d05-40bd-aa0b-3e12eb1e6585)

**Comment by Achazwl** [comment]
> No module named torch

You need to install torch first.
