### ISSUE TITLE
bmtrain compiling without torch

### ISSUE THREAD

**Issue by ithyl** [OpenBMB/BMTrain#114]
/usr/local/cuda-11.7/bin/nvcc -I/home/project/machineLearn/CPM-Bee/venv/lib/python3.10/site-packages/torch/include -I/home/project/machineLearn/CPM-Bee/venv/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/project/machineLearn/CPM-Bee/venv/lib/python3.10/site-packages/torch/include/TH -I/home/project/machineLearn/CPM-Bee/venv/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda-11.7/include -I/home/project/machineLearn/CPM-Bee/venv/include -I/usr/local/include/python3.10 -c csrc/cuda/has_inf_nan.cu -o build/temp.linux-x86_64-cpython-310/csrc/cuda/has_inf_nan.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=sm_50 -std=c++17
     csrc/cuda/has_inf_nan.cu(11): error: identifier "__heq" is undefined**

CH_EXTENSION_NAME=_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_50,code=sm_50 -std=c++17
      csrc/cuda/has_inf_nan.cu(11): error: identifier "__heq" is undefined

**Comment by guillaumexu** [comment]
同样的问题

**Comment by ithyl** [comment]
> 同样的问题

你显卡是啥，我以为我的显卡不行

**Comment by guillaumexu** [comment]
我的是M40，编译的话和显卡应该没关系吧

**Comment by ithyl** [comment]
> 我的是M40，编译的话和显卡应该没关系吧

那就不知道了，我以为我的里边缺啥东西

**Comment by guillaumexu** [comment]
我试了下colab，选的T4的显卡，还真的装上了，可能是显卡的问题

**Comment by guillaumexu** [comment]
但是colab上用清华的源发现也装不上，环境依赖是个玄学

**Comment by ithyl** [comment]
> 但是colab上用清华的源发现也装不上，环境依赖是个玄学
pip的源吗

**Comment by ithyl** [comment]
> 但是colab上用清华的源发现也装不上，环境依赖是个玄学

pip 源吗

**Comment by guillaumexu** [comment]
是的，你可以试试这个：
!pip uninstall torchaudio torchdata torchtext torchvision
!pip install torch==1.13+cu117 -f https://download.pytorch.org/whl/torch/
!git clone -b main --single-branch https://github.com/OpenBMB/CPM-Bee.git
!pip install -r /content/CPM-Bee/src/requirements.txt

**Comment by guillaumexu** [comment]
最后这个如果加上清华的源就不行

**Comment by guillaumexu** [comment]
但是家里的网络不加清华的源简直不能忍受

**Comment by ithyl** [comment]
> 但是家里的网络不加清华的源简直不能忍受

外边的源是那个呀

**Comment by ithyl** [comment]
> 但是家里的网络不加清华的源简直不能忍受

我pip的发现装完就是清华的源。0.0.

**Comment by guillaumexu** [comment]
global.disable-pip-version-check='True'
global.extra-index-url='https://us-python.pkg.dev/colab-wheels/public/simple/'
global.log='/var/log/pip.log'
list.format='columns'

**Comment by ithyl** [comment]
> global.disable-pip-version-check='True' global.extra-index-url='https://us-python.pkg.dev/colab-wheels/public/simple/' global.log='/var/log/pip.log' list.format='columns'

这个地址访问是404  这莫尴尬

**Comment by guillaumexu** [comment]
这个是谷歌用的源，可能要科学上网吧

**Comment by ithyl** [comment]
> 这个是谷歌用的源，可能要科学上网吧

我可访问外边

**Comment by ithyl** [comment]
> 这个是谷歌用的源，可能要科学上网吧

你在colab里curl下

**Comment by ithyl** [comment]
> 这个是谷歌用的源，可能要科学上网吧


(base) [root@TaoTi blade]# pip3 install bmtrain -i https://pypi.org/simple/pip/
我用这个也不行

**Comment by guillaumexu** [comment]
> 
我就是colab里查到的啊

**Comment by guillaumexu** [comment]
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/

**Comment by guillaumexu** [comment]
不是的
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from opendelta->-r /content/CPM-Bee/src/requirements.txt (line 8)) (1.10.1)
Collecting sklearn (from opendelta->-r /content/CPM-Bee/src/requirements.txt (line 8))
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7a/93/e0e1b1e98f39dfca7ec9795cb46f6e09e88a2fd5d4a28e4b3d1f618a2aec/sklearn-0.0.post5.tar.gz (3.7 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ithyl** [comment]
> 不是的 Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from opendelta->-r /content/CPM-Bee/src/requirements.txt (line 8)) (1.10.1) Collecting sklearn (from opendelta->-r /content/CPM-Bee/src/requirements.txt (line 8)) Downloading https://pypi.tuna.tsinghua.edu.cn/packages/7a/93/e0e1b1e98f39dfca7ec9795cb46f6e09e88a2fd5d4a28e4b3d1f618a2aec/sklearn-0.0.post5.tar.gz (3.7 kB) error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. Preparing metadata (setup.py) ... error error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.




不用colab报的是我上面那个错吗

**Comment by guillaumexu** [comment]
我在自己的电脑上是：
csrc/cuda/has_inf_nan.cu(11): error: identifier "__heq" is undefined
      
      1 error detected in the compilation of "csrc/cuda/has_inf_nan.cu".
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bmtrain
  Running setup.py clean for bmtrain
Failed to build bmtrain

**Comment by ithyl** [comment]
> 

这个应该跟显卡有关系，我的也是

**Comment by ithyl** [comment]
> 我在自己的电脑上是： csrc/cuda/has_inf_nan.cu(11): error: identifier "__heq" is undefined
> 
> ```
>   1 error detected in the compilation of "csrc/cuda/has_inf_nan.cu".
>   error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for bmtrain Running setup.py clean for bmtrain Failed to build bmtrain

这个应该跟显卡有关系，我的也是

**Comment by guillaumexu** [comment]
哦，你的显卡是什么？

**Comment by ithyl** [comment]
> 哦，你的显卡是什么？ 

gtx750ti 0.0

**Comment by guillaumexu** [comment]
算了，放弃了

**Comment by ithyl** [comment]
> 算了，放弃了

我看别人用他上边列出来的好像可以

**Comment by guillaumexu** [comment]
> 

哦，列出来什么？
不训练的话不装bmtrain也没关系。训练的话我的卡也慢的没用

**Comment by ithyl** [comment]
> > 
> 
> 哦，列出来什么？ 不训练的话不装bmtrain也没关系。训练的话我的卡也慢的没用

他官方readme 里写的几个显卡

**Comment by ithyl** [comment]
> > 
> 
> 哦，列出来什么？ 不训练的话不装bmtrain也没关系。训练的话我的卡也慢的没用

我买了个rtx3060 装了后就直接装上了

**Comment by guillaumexu** [comment]
没钱换显卡啊😂

ithyl ***@***.***> 于2023年6月29日周四 14:17写道：
