### ISSUE TITLE
安装BMTranin失败：nccl.obj : error LNK2001: XXXX

### ISSUE THREAD

**Issue by ShuaiLing-Shao** [OpenBMB/BMTrain#123]
`nvcc -V`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

`pip install bmtrain --no-cache-dir`

 "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\S\.conda\envs\pytorch-gpu\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64" /LIBPATH:C:\Users\S\.conda\envs\pytorch-gpu\libs /LIBPATH:C:\Users\S\.conda\envs\pytorch-gpu/LIBPATH:C:\Users\S\.conda\envs\pytorch-gpu\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\lib\x64" "/LIBPATH:C:\Program Fi
les (x86)\Windows Kits\NETFXSDK\4.7.2\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib 
/EXPORT:PyInit__C C:\Users\S\AppData\Local\Temp\pip-install-ghk5b7qs\bmtrain_d42f14bf47a44dbaa27b6b9221361ab3\build\temp.win-amd64-cpython-310\Release\csrc/nccl.obj /OUT:build\lib.win-amd64-cpython-310\bmtrain\nccl\_C.cp310-win_amd64.pyd /IMPLIB:C:\Users\S\AppData\Local\Temp\pip-install-ghk5b7qs\bmtrain_d42f14bf47a44dbaa27b6b9221361ab3\build\temp.win-amd64-cpython-310\Release\csrc\_C.cp310-win_amd64.lib
        正在创建库 C:\Users\S\AppData\Local\Temp\pip-install-ghk5b7qs\bmtrain_d42f14bf47a44dbaa27b6b9221361ab3\build\temp.win-amd64-cpython-310\Release\csrc\_C.cp310-win_amd64.lib 和对象 C:\Users\S\AppData\Local\Temp\pip-install-ghk5b7qs\bmtrain_d42f14bf47a44dbaa27b6b9221361ab3\build\temp.win-amd64-cpython-310\Release\csrc\_C.cp310-win_amd64.exp
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommInitRank
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduce
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclRecv
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupEnd
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclSend
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommCount
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetUniqueId
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommDestroy
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclBroadcast
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupStart
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommUserRank
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduceScatter
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclAllGather
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclAllReduce
      nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetErrorString
      build\lib.win-amd64-cpython-310\bmtrain\nccl\_C.cp310-win_amd64.pyd : fatal error LNK1120: 15 个无法解析的外部命令
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for bmtrain
  Running setup.py clean for bmtrain
Failed to build bmtrain
ERROR: Could not build wheels for bmtrain, which is required to install pyproject.toml-based projects

**Comment by MayDomine** [comment]
Windows is not support yet
