### ISSUE TITLE
gather result存在潜在问题

### ISSUE THREAD

**Issue by zkh2016** [OpenBMB/BMTrain#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

如果传入的tensor是其他大tensor的切片，gather时会报错："Buffer size not aligned"

### Environment Information

```markdown
- GCC version: 9.4.0
- Torch version: 1.13.1+cu117
- Linux system version: ubuntu 20.04
- CUDA version: 11.7
- Torch's CUDA version (as per `torch.cuda.version()`): 11.7
```

### To Reproduce

1. 构造一个大的tensor A
2. 构造一个小tensor B指向A的一个区间
3. gather_result(B)
4. 会出现“Buffer size not aligned"

### Expected Behavior

期望正在运行，返回正确结果

### Confirmation

- [ ] I have reviewed and verified all the information provided in this report.

**Comment by Achazwl** [comment]
Fixed in #146
