### ISSUE TITLE
[BUG] KeyError: 'LOCAL_RANK'

### ISSUE THREAD

**Issue by Kunlun-Zhu** [OpenBMB/BMTrain#19]
''''''
File "train.py", line 15, in main
    bmt.init_distributed(
  File "lib/python3.9/site-packages/bmtrain/init.py", line 40, in init_distributed
    local_rank = int(os.environ["LOCAL_RANK"])
  File "lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'
''''''
An Error occured when calling bmt.init_distributed function in train.py, 
After I check 'os.environ.keys()', couldn't find 'LOCAL_RANK'.
It seems that 'bmtrain' wasn't successfully installed

**Comment by Kunlun-Zhu** [comment]
python3 -m torch.distributed.launch --master_addr ${MASTER_ADDR} --master_port ${MASTER_PORT} --nproc_per_node ${GPU_PER_NODE} --nnodes ${NNODES} --node_rank ${NODE_RANK} train.py
It seems that I didn't set node_rank here correctly

**Comment by qinqinqaq** [comment]
hello，how did you solve the above bug
