### ISSUE TITLE
[BUILD ERROR] <title>lining failed in call to always_inline '__mm512_xxx_xxx'   xxxxxxxxx

### ISSUE THREAD

**Issue by lk137095576** [OpenBMB/BMTrain#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Build Error

build from source ERROR  pipe branch 
may error while build  bind.cpp/adam_cpu.hpp
my cpu: AMD EPYC 7742 64-Core Processor

### Expected Behavior

----

### To Reproduce

----

### Environment Information

```markdown
- Operating System version:20.04
- GCC version:9
- Pybind version:11
- CUDA version:11.8
- NVIDIA NCCL CU11 version:
- CMake version:3.16.3
- Pip version:22.3.1
```

### Installation Method

Source Code Installation

### Full Error Traceback

not available

### Confirmation

- [X] I have reviewed and verified all the information provided in this report.

**Comment by MayDomine** [comment]
Check if your cpu can support AVX512. If not , try `export BUILD_DOCKER_ENV = 1` and it will let compiler add avx512 flag instead of using native option.
