### ISSUE TITLE
[BUG] <HTTPError: 403 Client Error>

### ISSUE THREAD

**Issue by CearX** [OpenBMB/BMTrain#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug

File ~/.local/lib/python3.10/site-packages/model_center/utils/net_utils.py:63, in check_web_and_convert_path(path, load_type)
     [62](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/cearx/llm.c2/new/~/.local/lib/python3.10/site-packages/model_center/utils/net_utils.py:62) try:
---> [63](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/cearx/llm.c2/new/~/.local/lib/python3.10/site-packages/model_center/utils/net_utils.py:63)     requests.get(f'{url}/config.json', stream=True).raise_for_status() # use config.json to check if identifier is valid
     [64](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/cearx/llm.c2/new/~/.local/lib/python3.10/site-packages/model_center/utils/net_utils.py:64) except:

File ~/.local/lib/python3.10/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   [1020](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/cearx/llm.c2/new/~/.local/lib/python3.10/site-packages/requests/models.py:1020) if http_error_msg:
-> [1021](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/cearx/llm.c2/new/~/.local/lib/python3.10/site-packages/requests/models.py:1021)     raise HTTPError(http_error_msg, response=self)

HTTPError: 403 Client Error: Forbidden for url: https://openbmb.oss-cn-hongkong.aliyuncs.com/model_center/bert-base-uncased/config.json

### Environment Information

```markdown
- GCC version:11.4.0
- Torch version:2.4.0+cu121
- Linux system version:Ubuntu 22.04
- CUDA version:12.5
- Torch's CUDA version (as per `torch.cuda.version()`):12.1
```

### To Reproduce

https://github.com/OpenBMB/ModelCenter/blob/main/README-ZH.md#2-%E5%87%86%E5%A4%87%E6%A8%A1%E5%9E%8B

import torch
from model_center.model import Bert, BertConfig
from model_center.layer import Linear

class BertModel(torch.nn.Module):
    def __init__(self, config):
        super().__init__()
        self.bert = Bert.from_pretrained("bert-base-uncased")
        self.dense = Linear(config.dim_model, 2)
        bmt.init_parameters(self.dense)

    def forward(self, input_ids, attention_mask):
        pooler_output = self.bert(input_ids=input_ids, attention_mask=attention_mask).pooler_output
        logits = self.dense(pooler_output)
        return logits

config = BertConfig.from_pretrained("bert-base-uncased")
model = BertModel(config)

### Expected Behavior

HTTPError: 403 Client Error

### Additional Information

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>You have no right to access this object because of bucket acl.</Message>
<RequestId>66D6B27ED14BBC30392F06C5</RequestId>
<HostId>openbmb.oss-cn-hongkong.aliyuncs.com</HostId>
<EC>0003-00000001</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00000001</RecommendDoc>
</Error>

### Confirmation

- [X] I have reviewed and verified all the information provided in this report.

**Comment by Achazwl** [comment]
Our OSS cloud storage traffic has been exhausted, and we are currently making adjustments. We apologize for any inconvenience this may cause.

**Comment by Achazwl** [comment]
We have temporarily fix the OSS. Please try downloading it now to see if it works.

In the future, we will gradually migrate to a new storage and update the download links in the code.

**Comment by CearX** [comment]
download successful
