### ISSUE TITLE
[Bug]TypeError: gather() received an invalid combination of arguments

### ISSUE THREAD

**Issue by Kunlun-Zhu** [OpenBMB/BMTrain#24]
Hi developer, when I tried to use 'gather()' method from the 'Distributedparameter', I received the following error:
````
, line 43, in __init__
    self.rel_embed.weight /= torch.norm(self.rel_embed.weight.gather().detach(), p=self.p_norm, dim=-1)[:, None]
TypeError: gather() received an invalid combination of arguments - got (), but expected one of:
 * (int dim, Tensor index, *, bool sparse_grad)
 * (name dim, Tensor index, *, bool sparse_grad)
````
I coundn't find any information about this set of arguments required, any idea why this may occur or how may I solve this issue?
Thanks a lot.

**Comment by Kunlun-Zhu** [comment]
I Currently fixed this by 
````
self.rel_embed.weight.div_(torch.norm(self.rel_embed.weight, p=self.p_norm, dim=-1)[:, None])
````

**Comment by a710128** [comment]
This is probably incorrect. `self.rel_embed.weight` is not changed inplace by using div_. 
Due to the BMTrain implementation, `self.rel_embed.weight` does not return the parameter itself, but an "intermediate result".

**Comment by a710128** [comment]
There is currently no proper way to update the parameters during training. You can normalize " self.rel_embed" before each use.
