### ISSUE TITLE
[Bug] Tensor with a size of 1 being splitted incorrectly when broadcasting

### ISSUE THREAD

**Issue by alphaGem** [OpenBMB/BMTrain#33]
Say, I have a tensor `z` with a size of  `[1]`, and a tensor `x` with a size of `[batch_size, intermediate_dim, model_dim]`.

When calculating `z*x`, `z` should be broadcasted to the same size as x.

However, in the current implementation of BMTrain, if we have 4 GPUs, as far as I can see, `z` would be firstly split into tensors `z0`  to `z3` with sizes of `[1]`, `[0]`, `[0]`, `[0]`; and `x` would be also split into 4 tensors `x0` to `x3`. Then things like `zi*xi` would be calculated. However, `z1*x1` fails because the tensor `z1` with a size of `[0]` does not match the tensor x1 in size.

Code causing the problem would be attached later.

感觉英语有点工地，这是中文版本：

假如我有张量 `z`，大小是 `[1]`，还有张量 `x`，大小是 `[batch_size, intermediate_dim, model_dim]`。

算 `z*x` 的时候，`z` 应该被广播到 `x` 一样的大小。

但是在 BMTrain 现有的实现下，假设有 4 个 GPU，依我所见，`z` 会被切成四个张量 `z0` 到 `z3`，大小分别是 `[1]`, `[0]`, `[0]`, `[0]`; `x`  也会被切成四个张量 `x0` 到  `x3`。然后会算 `zi*xi`  之类的东西。但是 `z1*x1` 计算会失败，因为张量 `z1` 大小是 `[0]`，与张量 `x1` 大小不符。

产生问题的代码稍后附上。

**Comment by alphaGem** [comment]
### Code Causing the Problem

Run the code `test.py`
```
import bmtrain as bmt
import torch

bmt.init_distributed(seed=1)

z = bmt.DistributedParameter(torch.tensor(0.5))
x = bmt.DistributedParameter(torch.rand(10))

bmt.synchronize()

res = z*x
```
with command
```
torchrun --nnodes=1 --nproc_per_node=4 test.py 
```

### Behavior

Expected behavior: program exits normally.

Actual behavior: raised the following error:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    res = z*x
RuntimeError: The size of tensor a (0) must match the size of tensor b (3) at non-singleton dimension 0
```

**Comment by a710128** [comment]
try `res = z.gather()*x.gather()`
DistributedParameter should be gathered manually if it's not in a DistributedModule.
