### ISSUE TITLE
请教训练时长

### ISSUE THREAD

**Issue by RyanYip-Kat** [OpenBMB/BMTrain#55]
![1669192431605](https://user-images.githubusercontent.com/67267063/203501930-aa02ba19-88d2-4ba9-94d2-9663c70acb1e.jpg)
请问您的这个表格里面，该模型的训练时长是多少呢？

**Comment by xiaoguaishoubaobao** [comment]
> 一个月左右的时间

8卡v100 一个月 好恐怖
