### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by wccccp** [OpenBMB/BMTrain#58]
ERROR: Command errored out with exit status 1: 'C:\Users\46213\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\46213\\AppData\\Local\\Temp\\pip-install-0s5mkooc\\bmtrain_23dc03e3d7e841b88ef095cfb3ede34b\\setup.py'"'"'; __file__='"'"'C:\\Users\\46213\\AppData\\Local\\Temp\\pip-install-0s5mkooc\\bmtrain_23dc03e3d7e841b88ef095cfb3ede34b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\46213\AppData\Local\Temp\pip-record-z5irnjba\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\46213\anaconda3\Include\bmtrain' Check the logs for full command output.

**Comment by a710128** [comment]
BMTrain does not currently support Windows.
