### ISSUE TITLE
Segment fault when the code ends

### ISSUE THREAD

**Issue by lhj-git** [OpenBMB/BMTrain#66]
When using bmtrain to train my model, the code successfullt run to the last line but give me a segment fault.
![image](https://user-images.githubusercontent.com/72364657/215935249-ce9dcb43-d0aa-4ce5-a581-167c21cb08e6.png)

**Comment by a710128** [comment]
Does `torchrun` work well without bmtrain?

**Comment by lhj-git** [comment]
No, it tells me about segment fault even with an empty python file

**Comment by a710128** [comment]
It looks like this is a bug in torchrun and not a bug in bmtrain.
