### ISSUE TITLE
How can I apply checkpoint block on cpm-1? 

### ISSUE THREAD

**Issue by lhj-git** [OpenBMB/BMTrain#67]
The code like this always give me a div 0 error in cpm line
![image](https://user-images.githubusercontent.com/72364657/216210858-1beb00b3-861b-44eb-b621-4fc8a114fdac.png)

**Comment by a710128** [comment]
CheckpointBlock should be applied to each `decoder layer` of the model.
See the example https://github.com/OpenBMB/BMTrain/blob/0.2.1/example/models/gpt.py

**Comment by lhj-git** [comment]
> CheckpointBlock should be applied to each `decoder layer` of the model. See the example https://github.com/OpenBMB/BMTrain/blob/0.2.1/example/models/gpt.py

Does that mean I should implement cpm1 in each layer? But how can I use the pretrained cpm1 parameters with limited memory of GPU.

**Comment by a710128** [comment]
In fact, we have a `bmtrain.BMTrainModelWrapper` still in testing that automatically adapts the model to BMTrain.
https://github.com/OpenBMB/BMTrain/blob/0.2.1/bmtrain/wrapper.py#L35
It works fine on most of the models in transformers.
