### ISSUE TITLE
install error on windows10

### ISSUE THREAD

**Issue by DN1204** [OpenBMB/BMTrain#71]
python setup.py install
running install
running bdist_egg
running egg_info
writing bmtrain.egg-info\PKG-INFO
writing dependency_links to bmtrain.egg-info\dependency_links.txt
writing requirements to bmtrain.egg-info\requires.txt
writing top-level names to bmtrain.egg-info\top_level.txt
reading manifest file 'bmtrain.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bmtrain.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'bmtrain.nccl._C' extension
Emitting ninja build file D:\code\python\nlp\BMTrain-main\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
F:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:F:\Python\Python37\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64" /LIBPATH:F:\Python\Python37\libs /LIBPATH:F:\Python\Python37\PCbuild\amd64 "/LIBPATH:F:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\lib\x64" "/LIBPATH:F:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22000.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22000.0\\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit__C D:\code\python\nlp\BMTrain-main\build\temp.win-amd64-3.7\Release\csrc/nccl.obj /OUT:build\lib.win-amd64-3.7\bmtrain\nccl\_C.cp37-win_amd64.pyd /IMPLIB:D:\code\python\nlp\BMTrain-main\build\temp.win-amd64-3.7\Release\csrc\_C.cp37-win_amd64.lib
  正在创建库 D:\code\python\nlp\BMTrain-main\build\temp.win-amd64-3.7\Release\csrc\_C.cp37-win_amd64.lib 和对象 D:\code\python\nlp\BMTrain-main\build\temp.win-amd64-3.7\Release\csrc\_C.cp37-win_amd64.exp
nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommInitRank
nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduce
nccl.obj : error LNK2001: 无法解析的外部符号 ncclRecv
nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupEnd
nccl.obj : error LNK2001: 无法解析的外部符号 ncclSend
nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommCount
nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetUniqueId
nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommDestroy
nccl.obj : error LNK2001: 无法解析的外部符号 ncclBroadcast
nccl.obj : error LNK2001: 无法解析的外部符号 ncclGroupStart
nccl.obj : error LNK2001: 无法解析的外部符号 ncclCommUserRank
nccl.obj : error LNK2001: 无法解析的外部符号 ncclReduceScatter
nccl.obj : error LNK2001: 无法解析的外部符号 ncclAllGather
nccl.obj : error LNK2001: 无法解析的外部符号 ncclAllReduce
nccl.obj : error LNK2001: 无法解析的外部符号 ncclGetErrorString
build\lib.win-amd64-3.7\bmtrain\nccl\_C.cp37-win_amd64.pyd : fatal error LNK1120: 15 个无法解析的外部命令
error: command 'F:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

cuda 11.7
torch                   1.13.1+cu117
torchaudio              0.13.1+cu117
torchvision             0.14.1+cu117
vs 2022

I can't find a solution. I tried different versions of torch and vs.
试了很多个版本的torch vs，还是不行，是因为cuda版本太高了吗？我显卡是3070，windows这么难编译的吗

**Comment by a710128** [comment]
#54 
BMTrain目前还无法直接在windows环境下安装，推荐在windows系统上使用WSL，可以在WSL中安装。

**Comment by xiaoguaishoubaobao** [comment]
> #54 BMTrain目前还无法直接在windows环境下安装，推荐在windows系统上使用WSL，可以在WSL中安装。

好的呢 学到了
