### ISSUE TITLE
禁用ZeRO Optimization

### ISSUE THREAD

**Issue by yiye3** [OpenBMB/BMTrain#76]
在使用该框架的时候，默认使用了zero optimization，backward时间是forward的3倍左右，以换取更少的显存占用；如果不缺显存的话，我希望获得更快的训练速度，请问我怎样禁用zero optimization呢？

**Comment by a710128** [comment]
zero optimization不会显著减慢训练速度，如果想要提升训练速度可以尝试不用Checkpointing，这样能避免在backward的时候进行重计算。
