### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by zhhongzhi** [OpenBMB/BMTrain#83]
`ValueError: Unknown CUDA arch (9.0+PTX) or GPU not supported`

`nvcc --version 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0`

**Comment by a710128** [comment]
Did you set the TORCH_CUDA_ARCH_LIST environment variable?

**Comment by zhhongzhi** [comment]
echo $TORCH_CUDA_ARCH_LIST
5.2 6.0 6.1 7.0 7.5 8.0 8.6 9.0+PTX

should I remove 9.0+PTX?

**Comment by a710128** [comment]
yes, try `6.0 6.1 7.0 7.5 8.0 8.6+PTX`

**Comment by zhhongzhi** [comment]
It works. Thank you so much.
