### ISSUE TITLE
BUG:TypeError: linear(): argument 'input' (position 1) must be Tensor, not NoneType

### ISSUE THREAD

**Issue by pilipala818** [OpenBMB/BMTrain#87]
several error occur, when I try to reproduce the project  
https://modelcenter.readthedocs.io/en/latest/notes/quickstart.html

1.TypeError__init__() got an unexpected keyword argument 'architectures'
It seems like Hugging face update the configuration file. Problem fixed when I empty configuration file.

2.TypeError: linear(): argument ‘input‘ (position 1) must be Tensor, not NoneType
Traceback prompt that it occur from 
logits = model(input_ids, attention_mask)
 ...
TypeError: linear(): argument ‘input‘ (position 1) must be Tensor, not NoneType
    return torch._C._nn.linear(input, weight, bias)

**Comment by Achazwl** [comment]
Seems dataset related bug. Try examples in https://github.com/OpenBMB/ModelCenter/tree/main/examples
