### ISSUE TITLE
BMtrain insatll failed which my environment is gcc5.4.0, torch1.7.0, cudnn10.2. I have try other torch version, for example 1.12.0, filed again. 

### ISSUE THREAD

**Issue by rongzhenlee** [OpenBMB/BMTrain#88]
error massage: csrc/adam_cpu.cpp: 158:27 error const class at::tensor has no member named is_cpu

**Comment by a710128** [comment]
Pytorch 1.7.0 is not supported. 

But I tried to install bmtrain on pytorch 1.12.1 and it installed fine. 

Can you give some error messages?
