### ISSUE TITLE
[问题]优化器状态加载

### ISSUE THREAD

**Issue by ftgreat** [OpenBMB/BMTrain#93]
多机并行训练（zero3）保存ckpt时会保存每个cpu对应的optim状态到 file.${bmt.rank()}。
加载优化器继续训练时遇到shape不对的问题，想问下什么原因？
重新启动时master节点不变，各节点的node rank也没有改变。
![image](https://user-images.githubusercontent.com/10432020/236612006-3255cf9b-01c8-4ee7-a8a4-3e07b59275ea.png)

**Comment by Achazwl** [comment]
Is your bmtrain version 0.2.1 and the optimizer is AdamOptimizer instead of AdamOffloadOptimizer? If yes, the bug should have been fixed in the new version 0.2.2.
However, it seems that your error occurs in the backward phase but not the optimizer phase.

**Comment by ftgreat** [comment]
bmtrain version is 0.2.0 and AdamOffloadOptimizer was uesd.

**Comment by Achazwl** [comment]
The bug occurred during the save phase, so it's probably not compatible.

**Comment by ftgreat** [comment]
> The bug occurred during the save phase, so it's probably not compatible.

现有optimizer states保存了每个rank的state。
有手动方法修改下现有optimizer states，能适配到 version 0.2.2 加载么？谢谢 @Achazwl

**Comment by ftgreat** [comment]
> Is your bmtrain version 0.2.1 and the optimizer is AdamOptimizer instead of AdamOffloadOptimizer? If yes, the bug should have been fixed in the new version 0.2.2. However, it seems that your error occurs in the backward phase but not the optimizer phase.

请问fix关联到哪个PR，谢谢

**Comment by Achazwl** [comment]
https://github.com/OpenBMB/BMTrain/pull/68

**Comment by ftgreat** [comment]
> The bug occurred during the save phase, so it's probably not compatible.

现有optimizer states保存了每个rank的state。
有手动方法修改下现有optimizer states，能适配到 version 0.2.2 正常加载么？谢谢

@Achazwl

**Comment by Achazwl** [comment]
I think it's possible to save a state in the new version and compare it with the old version, deleting any extra keys in the old version that don't exist in the new version.

**Comment by ftgreat** [comment]
请问2个问题，麻烦您有空看下，谢谢：
1. 基于16节点训练并保存优化器状态，可以使用8节点加载优化器状态么，有转换工具么？
2. 如果模型很大（单机内存&显存受限），按照配置构建模型支持动态shard吗，有相关的例子么？
