### ISSUE TITLE
【Error】 in Adam implementation

### ISSUE THREAD

**Issue by marscrazy** [OpenBMB/BMTrain#96]
我看到有一个scale实现上的错误，可能会导致 Nan的问题。
![image](https://github.com/OpenBMB/BMTrain/assets/4392184/dbf9ee3e-9612-4540-8bce-7a68495ccd8e)

这个eps\*scale 应该需要 是 eps\*sqrtf(scale）
https://github.com/OpenBMB/BMTrain/blob/9cc975593f628a3fcc8c71328081e238914eca1d/csrc/cuda/adam.cu#LL29C115-L29C115

**Comment by Achazwl** [comment]
in the code, `local_m = real_m * scale` and `local_v = real_v * scale`, so `sqrtf(local_v * scale)` get `scale * sqrtf(realv)`. Therefore it should add `eps * scale` .

**Comment by marscrazy** [comment]
Thank you, this makes it clearer to me.
