### ISSUE TITLE
Can BMTrain work with Megatron-LM?

### ISSUE THREAD

**Issue by marscrazy** [OpenBMB/BMTrain#97]
We want to try a large LM model (>30B).
Are there any examples to do that?

**Comment by Achazwl** [comment]
[ModelCenter](https://github.com/OpenBMB/ModelCenter/tree/main), based on bmtrain,
support LLaMA
by first converting checkpoint files using (https://github.com/OpenBMB/ModelCenter/blob/main/transfer/hugLLaMa_bmtrainLLaMa.py)
then inference (https://github.com/OpenBMB/ModelCenter/blob/main/tests/test_llama.py)
of finetune (https://github.com/OpenBMB/ModelCenter/blob/main/examples/llama/finetune_llama.py).

If you want pre-training, you can write a new model config and a new model based on [those layers in modelcenter
](https://github.com/OpenBMB/ModelCenter/tree/main/model_center)
