### ISSUE TITLE
Does BMTrain 0.2.0 support cuda 11.1?

### ISSUE THREAD

**Issue by FutureForMe** [OpenBMB/BMTrain#98]
In the environment of pytorch 1.12.1, cuda 11.1, and python 3.8.0, I failed to install BMTrain 0.2.0 using "pip setup.py install". Prompt that cuda needs to meet version 11.3. Does BMTrain 0.2.0 support cuda 11.1?

**Comment by MayDomine** [comment]
BMTrain now needs that the CUDA version used to compile your Torch C++ plugin matches the runtime version of your current CUDA Toolkit, you can use the following Python command:

```
import torch
print(torch.version.cuda)
```
This command will print the CUDA version that was used to compile PyTorch. Please ensure that this version matches the version of your installed CUDA Toolkit.
You can check the cuda runtime version by using `nvcc --version` command.
We will fix this dependency problem in next version.
